### ISSUE TITLE
Fix problems with deploy script crashing on some repos

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord-dev/door43.org#599]
When touching the build_log.json files, saw a bunch of deploy crashes.  This is one example crash from /photonomad0/ar_eph_text_ulb/39a099622d:

/aws/lambda/tx_door43_deploy [DEBUG]	2017-06-30T14:14:26.841Z	ff4cef15-5d9d-11e7-a796-4bc0a808c0be	Downloading templates/project-page.html to /tmp/deployer_sADt8u/template_pMZKWc/project-page.html...
/aws/lambda/tx_door43_deploy [DEBUG]	2017-06-30T14:14:27.309Z	ff4cef15-5d9d-11e7-a796-4bc0a808c0be	Applying template to /tmp/deployer_sADt8u/source_H2jl2r/u/photonomad0/ar_eph_text_ulb/39a099622d/50-EPH.html.
/aws/lambda/tx_door43_deploy [ERROR]	2017-06-30T14:14:27.528Z	ff4cef15-5d9d-11e7-a796-4bc0a808c0be	list index out of range
Traceback (most recent call last):
  File "/var/task/libraries/lambda_handlers/handler.py", line 28, in handle
    return self._handle(event, context)
  File "/var/task/libraries/lambda_handlers/door43_deploy_handler.py", line 20, in _handle
    self.deploy(bucket_name, key)
  File "/var/task/libraries/lambda_handlers/door43_deploy_handler.py", line 40, in deploy
    ProjectDeployer(cdn_bucket, door43_bucket).deploy_revision_to_door43(key)
  File "/var/task/libraries/door43_tools/project_deployer.py", line 120, in deploy_revision_to_door43
    do_template(resource_type, source_dir, output_dir, template_file)
  File "/var/task/libraries/door43_tools/templaters.py", line 22, in do_template
    return templater.run()
  File "/var/task/libraries/door43_tools/templaters.py", line 47, in run
    self.apply_template()
  File "/var/task/libraries/door43_tools/templaters.py", line 168, in apply_template
    right_sidebar_html = self.build_right_sidebar(filename)
  File "/var/task/libraries/door43_tools/templaters.py", line 62, in build_right_sidebar
    html = self.build_page_nav(filename)
  File "/var/task/libraries/door43_tools/templaters.py", line 235, in build_page_nav
    chapter['id'].split('-')[2].lstrip('0'))
IndexError: list index out of range/aws/lambda/tx_door43_deploy Bad Request: list index out of range: EnvironmentError
Traceback (most recent call last):
  File "/var/task/main.py", line 12, in handle
    return Door43DeployHandler().handle(event, context)
  File "/var/task/libraries/lambda_handlers/handler.py", line 31, in handle
    raise EnvironmentError('Bad Request: {}'.format(e.message))
EnvironmentError: Bad Request: list index out of range

**Comment by PhotoNomad0** [comment]
Investigating to see if this is still a problem.

**Comment by PhotoNomad0** [comment]
Not seeing this problem anymore.  Suspect it was due to timeouts that have been addressed with changes to tx conversion pipeline.

think we can close this.
